### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by regexident**
Hi Suchin,

I took the liberty to remove some compiler warnings and clean up main.rs a bit.

Hope you don't mind the latter.

Oh, and I removed the `target_os` limitation. Callgrind runs quite well on OS X (and probably all other *NIX systems alike).

Vincent

### CODE REVIEW

**Comment by kernelmachine** [comment]
Hey Vincent -- good catches, thanks for this!

**Comment by regexident** [comment]
I have to say thanks! I was in dire need of a rusty profiler last week. Perfect timing!

**Comment by kernelmachine** [comment]
@regexident Did your pull request re cleanup compile successfully on your machine? I found that there were a bunch of move errors in main after you refactored the clap assembly. I reverted the merge, if you can look into it and re-submit the PR I'd really appreciate it. Travis would make this much easier, but I didn't have time yesterday to integrate it.

**Comment by regexident** [comment]
Uh, my bad. Shame on me. I was sure I'd successfully compiled the PR in its final state.

I made a new fixed PR: https://github.com/pegasos1/cargo-profiler/pull/5

**Pull request merged**
